import ChatHeader from "./ChatHeader"
import ChatMessage from "./ChatMessage"
import ChatInput from "./ChatInput"
import { ChatMessage as Msg } from "./interface"
import { SeriesEnum, StatusEnum } from "../../../../types/Series"
import LanguageEnum from "../../../../enums/LanguageEnum"

const USERS = {
    miyuna: {
        id: "bot",
        name: "Miyuna AI",
        role: "Virtual Assistant",
        avatar: "https://i.imgur.com/Z6X6ZQF.png",
        isBot: true,
        nameColor: "#60a5fa"
    },
    admin: {
        id: "1",
        name: "Ananda",
        role: "Project Owner",
        avatar: "https://i.pravatar.cc/150?img=3",
        isAdmin: true,
        nameColor: "#f87171"
    },
    dev: {
        id: "2",
        name: "Raka",
        role: "Frontend Dev",
        avatar: "https://i.pravatar.cc/150?img=8",
        nameColor: "#34d399"
    },
    member: {
        id: "3",
        name: "Salsa",
        role: "Member",
        avatar: "https://i.pravatar.cc/150?img=5",
        nameColor: "#facc15"
    }
}

const EMBED_COLOR = {
    link: "#6366f1",
    image: "#22c55e",
    video: "#ef4444",
    info: "#eab308",
    ai: "#60a5fa"
}


const messages: Msg[] = [
    {
        id: "1",
        sender: USERS.admin,
        content: "Oke team, hari ini fokus ke UI chat ya.",
        createdAt: ""
    },
    {
        id: "2",
        sender: USERS.dev,
        content: "Siap. Aku handle animation & layout.",
        createdAt: ""
    },
    {
        id: "3",
        sender: USERS.member,
        content: "Aku bantu testing mobile view 🙌",
        createdAt: ""
    },
    {
        id: "4",
        sender: USERS.miyuna,
        content: "Aku siap membantu dokumentasi & logic AI ✨",
        createdAt: ""
    },
    {
        id: "sys1",
        type: "system",
        content: "📌 Pesan penting telah dipin oleh Admin",
        createdAt: ""
    },
    {
        id: "5",
        sender: USERS.dev,
        content: "Cek referensi UI ini",
        embed: {
            type: "link",
            title: "Discord UI Guidelines",
            description: "Reference for spacing, interaction & UX",
            url: "https://discord.com",
            siteName: "discord.com",
            accentColor: EMBED_COLOR.link
        },
        createdAt: ""
    },
    {
        id: "m1",
        sender: USERS.dev,
        content: "Aku pakai referensi ini buat embed system",
        embed: {
            type: "link",
            title: "Open Graph Metadata",
            description: "How OG tags work for link previews",
            url: "https://ogp.me/",
            siteName: "ogp.me",
            accentColor: "#6366f1",
            collapsible: true
        },
        createdAt: ""
    },
    {
        id: "m2",
        sender: USERS.miyuna,
        embed: {
            type: "ai",
            title: "AI Summary",
            description:
                "Embed system sudah mendukung link, image, video, code, event, dan warning. Siap untuk realtime & auto-preview.",
            accentColor: "#60a5fa",
            footer: "Generated by Miyuna AI"
        },
        createdAt: ""
    },
    {
        id: "m3",
        sender: USERS.dev,
        embed: {
            type: "code",
            title: "Embed Interface",
            description:
                "export interface EmbedData { type: EmbedType; title?: string }",
            accentColor: "#22c55e",
            collapsible: true
        },
        createdAt: ""
    },
    {
        id: "m4",
        sender: USERS.admin,
        embed: {
            type: "event",
            title: "UI Review Meeting",
            description: "Diskusi final UI Chat & Embed System",
            fields: [
                { name: "Tanggal", value: "2 Februari 2026" },
                { name: "Jam", value: "20:00 WIB" },
                { name: "Platform", value: "Discord / Meet" }
            ],
            accentColor: "#eab308",
            footer: "Created by Admin"
        },
        createdAt: ""
    },
    {
        id: "m5",
        sender: USERS.admin,
        embed: {
            type: "warning",
            title: "Perhatian",
            description:
                "Dilarang share link eksternal tanpa izin admin.",
            accentColor: "#ef4444"
        },
        createdAt: ""
    },
    {
        id: "m6",
        sender: USERS.member,
        embed: {
            type: "image",
            title: "Preview Chat UI",
            image:
                "https://images.unsplash.com/photo-1611162618071-b39a2ec055d3",
            accentColor: "#22c55e"
        },
        createdAt: ""
    },
    {
        id: "m10",
        sender: USERS.dev,
        content: "**Rekomendasi manga bagus:** _romance + drama_",
        series: {
            id: "199720",
            title: "Bye-Bye Mizuhara",
            alternativeTitle: ["バイバイ水原"],
            url: "https://anilist.co/manga/199720",
            cover: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx199720-Kh36ArIiKLxb.jpg",
            type: SeriesEnum.Manga,
            language: LanguageEnum.JAPANESE,
            genres: ["Romance"],
            status: StatusEnum.Ongoing,
            author: ["Author A"],
            release: "2024",
            chapters: [],
            synopsis: "Kisah romansa remaja dengan konflik emosional."
        },
        reactions: [
            { emoji: "❤️", count: 3 },
            { emoji: "🔥", count: 1, reactedByMe: true }
        ],
        createdAt: ""
    }
]

export default function ChatPage() {
    return (
        <div className="h-screen bg-zinc-950 flex flex-col text-white">
            <ChatHeader
                user={{
                    name: "Miyuna Project",
                    role: "Group Chat",
                    avatar: "https://i.imgur.com/Z6X6ZQF.png"
                }}
            />

            <div className="bg-yellow-500/10 text-yellow-400 text-xs px-4 py-2 flex items-center gap-2">
                📌 UI Chat v1.0 – Focus: Group Chat & AI
            </div>


            <div className="flex-1 overflow-y-auto py-6 space-y-6">
                {messages.map(m => (
                    <ChatMessage key={m.id} msg={m} />
                ))}
            </div>

            <div className="flex items-center gap-2 px-4 text-sm text-zinc-400">
                <span className="w-2 h-2 bg-indigo-400 rounded-full animate-pulse" />
                Miyuna AI sedang mengetik...
            </div>


            <ChatInput />
        </div>
    )
}