name: Build Cordova Android & Electron

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Setup Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '18'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Install Cordova
        run: npm install -g cordova
      
      - name: Add Android platform
        run: cordova platform add android@latest
        working-directory: ./cordova

      - name: Install dependencies
        run: npm install
        working-directory: ./cordova

      - name: Build Android APK
        run: cordova build android --release
        working-directory: ./cordova

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: android-apk
          path: cordova/platforms/android/app/build/outputs/apk/release/*.apk

  build-electron-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '18'
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      
      - name: Add repository
        run: sudo add-apt-repository universe && sudo apt update
      
      - name: Setup environment
        run: sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm libarchive-tools snapd

      - name: Setup environment (Snapcraft)
        run: |
          sudo snap install snapcraft --classic
          sudo snap install multipass --beta --classic

      - name: Install Cordova
        run: npm install -g cordova
        working-directory: ./cordova

      - name: Install dependencies
        run: npm install
        working-directory: ./cordova

      - name: Add Electron platform
        run: cordova platform add electron
        working-directory: ./cordova

      - name: Build Electron for Linux
        run: npm run build
        working-directory: ./cordova

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: electron-linux
          path: |
            cordova/dist/*.deb
            cordova/dist/*.AppImage
            cordova/dist/*.snap
            cordova/dist/*.rpm
            cordova/dist/*.pacman
            cordova/dist/*.tar.gz

  build-electron-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova
        working-directory: ./cordova

      - name: Install dependencies
        run: npm install
        working-directory: ./cordova

      - name: Add Electron platform
        run: cordova platform add electron
        working-directory: ./cordova

      - name: Build Electron for Windows
        run: npm run build
        working-directory: ./cordova

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: electron-windows
          path: |
            cordova/dist/*.exe
            cordova/dist/*.msi